apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-cluster-role
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
    - nodes
    - events
    - services
    - configmaps
  verbs:
    - get
    - watch
    - list
- apiGroups: ["apps"]
  resources:
    - replicasets
    - deployments
    - daemonsets
  verbs:
    - get
    - list
    - watch
