apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: elk
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
  - name: beats
    port: 5044
    targetPort: 5044
    protocol: TCP
  - name: monitoring
    port: 9600
    targetPort: 9600
    protocol: TCP
  type: ClusterIP
